### ISSUE TITLE
issue with sapper and statically generated sites

### ISSUE THREAD

**Issue by AndreaPravato** [SharifClick/svelte-swipe#10]
Hi! This is a nice component. I have tried using it in sapper, running the project with "npm run dev"; all fine. I am using the slider in index.svelte. With "npm run export" (to get a statically generated site), though, I get a red (500) index.html in the console; then with npx serve __sapper__/export the slider looks fine in the website, but I notice that the blog section (I am using something similar to this one https://github.com/Charca/sapper-blog-template) of the site does not work anymore; I get a 500 error in blog page. svelte-sapper is installed as a dev dependency. I have tried removing svelte-sapper and after exporting the site, the blog section is up again. So, it looks like using this component breaks something in the sapper export process. The issue may not be related to this component (misstep in my config; conflicts of some sort; bugs in sapper, I do not know yet)

**Comment by SharifClick** [comment]
Hi @AndreaPravato , Please share your repo or up an example repo for us.
Thank you.
