### ISSUE TITLE
_svelteSwipe.Swipe is not a constructor

### ISSUE THREAD

**Issue by mylastore** [SharifClick/svelte-swipe#11]
I am getting this error I am running the default example implementation 
```
TypeError: _svelteSwipe.Swipe is not a constructor
```

**Comment by SharifClick** [comment]
Hi @mylastore , please share the repo that are you using.

**Comment by mylastore** [comment]
> Hi @mylastore , please share the repo that are you using.

here is the repo
[REPO](https://github.com/mylastore/parcel-svelte)

**Comment by mylastore** [comment]
By the way works with Svelte/Rollup but does not with Svelte/Parcel

**Comment by mylastore** [comment]
I made it to work with Pacrcel by updating your rollup-config.js  output format from 'es' to 'iife'

```
export default [
	{
		input: 'src/Swipe.svelte',
		output: [
			{ file: pkg.module, 'format': 'iife' },
			{ file: pkg.main, 'format': 'umd', name: 'Swipe' }
		],
		plugins: [
			svelte(),
			commonjs(),
      resolve(),
      terser(),
      bundleSize()
		]
	}
];
```
