### ISSUE TITLE
Not a bug but possibly a feature request

### ISSUE THREAD

**Issue by mylastore** [SharifClick/svelte-swipe#12]
I am creating a E-commerce with Svelte and on the product gallery I am trying to used your svelte-swipe how can I instead of the indicators been just dots, I want the product thumbnails see image below. 

<img width="950" alt="product" src="https://user-images.githubusercontent.com/8906338/79530488-47ccbf00-8024-11ea-9916-c11a9c4aa662.png">

**Comment by SharifClick** [comment]
You can make a thumbnails div below swipe holder and change swipe item functionally by catching click event on every thumbnail 
https://github.com/SharifClick/svelte-swipe#programmatically-change-slides

: maybe i will make a demo for this in that weekend

**Comment by SharifClick** [comment]
update: found a bug in `goTo` , will fix asap, and will make a demo for this,  thanks

**Comment by mylastore** [comment]
> update: found a bug in `goTo` , will fix asap, and will make a demo for this, thanks

Thank you this an awesome repo

**Comment by SharifClick** [comment]
Hi , just released new version with some requested features 
here is release changelog https://github.com/SharifClick/svelte-swipe/blob/master/CHANGELOG.md#160
here you will find uses https://github.com/SharifClick/svelte-swipe/blob/master/dev/App.svelte

Put a comment for bugs or new feature request, Hope you will find this package useful for you ::smiley::

**Comment by SharifClick** [comment]
hi @mylastore , A simple example I made for you 
https://svelte.dev/repl/be477862ac8b4dfea4c8e454e556ef2c?version=3.20.1

**Comment by mylastore** [comment]
> hi @mylastore , A simple example I made for you
> https://svelte.dev/repl/be477862ac8b4dfea4c8e454e556ef2c?version=3.20.1

AWESOME!!!!! Thank you for taking the time.
