### ISSUE TITLE
3D Transition

### ISSUE THREAD

**Issue by niklasgrewe** [SharifClick/svelte-swipe#17]
Hi,
thanks for this repo 👍

i found this cool 3D Carousel Animation, created with swiperjs:
https://codepen.io/corvus-007/pen/gQEzYW

possible to integrate this animation in svelte-swipe?

**Comment by SharifClick** [comment]
Hi, Thank you.
svelte-swipe has minimal use case, for fancy animation thing you can use swiper js itself. 
swiper is more stable and community tested.
