### ISSUE TITLE
The active_item doesn't update after window resize 

### ISSUE THREAD

**Issue by svirgunvolodia** [SharifClick/svelte-swipe#25]
After the `resize` event listener triggered SwipeItem is set to `defaultIndex` but `active_item` doesn't update

My configuration:
```
  const SLIDERS_NUMBER = 3;
  let transitionDuration = 500;
  let defaultIndex = 0;
  let active_item = 0;
```

![Svelte app](https://user-images.githubusercontent.com/37771765/95308519-b16ead00-0892-11eb-99b5-7e0e1ed9d30b.gif)

**Comment by SharifClick** [comment]
Thanks @svirgunvolodia , resize shouldn't be affect on functionality.
