### ISSUE TITLE
is there a way to make the Swipe height automatically follow the SwipeItem children?

### ISSUE THREAD

**Issue by lamualfa** [SharifClick/svelte-swipe#27]

**Comment by alesvaupotic** [comment]
+1

**Comment by SharifClick** [comment]
There is no api implemented yet, 
but you can achieve this by tracking clientWidth of children item by powering swipe-holder's style.height.

**Comment by SharifClick** [comment]
Thanks All
This issue fixed with PR #42 
Cheers
