### ISSUE TITLE
 missing documentation for Custom Thumbnail

### ISSUE THREAD

**Issue by espansione8** [SharifClick/svelte-swipe#28]
here http://sharifahmed.me/svelte-swipe/ there is the example for Custom Thumbnail, but in the doc the aren't any reference in the config props or a way to bind any "onclick" event to a specific image like the standard indicators.

**Comment by SharifClick** [comment]
https://svelte.dev/repl/be477862ac8b4dfea4c8e454e556ef2c?version=3.20.1
Hi @espansione8 , I made a repl a while ago, it may help you. 
Cheers

**Comment by espansione8** [comment]
Hi, I already added goTo(i) into my project and it's working fine with Bulma css.
I would suggest to add your repl https://svelte.dev/repl/be477862ac8b4dfea4c8e454e556ef2c?version=3.20.1 to the readme so the people can find it easily
