### ISSUE TITLE
import fails: "<Swipe> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules"

### ISSUE THREAD

**Issue by pixeline** [SharifClick/svelte-swipe#33]
```
import { Swipe, SwipeItem } from "svelte-swipe"; 
```
Generates the following error message:

> <Swipe> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Following [this suggestion](https://www.gitmemory.com/issue/c0bra/svelma/3/500437551), I tried specifically pointing to the .svelte files, to no avail.

**Comment by SharifClick** [comment]
PR #32 merged
