### ISSUE TITLE
Is there a way to make it loop infinitely?

### ISSUE THREAD

**Issue by FractalHQ** [SharifClick/svelte-swipe#34]
When autoplaying, it's quite jarring when it reaches the end and flies through 30+ images back to the beginning.  Is there a way to make it keep looping?

**Comment by SharifClick** [comment]
It would be better for me if you reproduce that bug on svelte repl. maybe with unplash images.

**Comment by axmad386** [comment]
Some problem here
It's not a bug, may be just feature request.
On this current version, when we have for example 5 slides. From slide 1, svelte-swipe will make slide to the right (to slide 2, and so on). When we reach the end of slides (Slide 5), svelte-swipe will back to slide 1 but in reverse direction (left), so it will go through slide 4 -> 3 -> 2 and then 1. May be is better to clone the 1st slide to end of array or something so the slide direction is still on right (not backwards).  We can see this feature in library like Slick Carousel on loop mode.

**Comment by FractalHQ** [comment]
@axmad386 Ah yes, that is what I was asking.  Sorry for not clarifying!
