### ISSUE TITLE
On change event handler?

### ISSUE THREAD

**Issue by patrickjquinn** [SharifClick/svelte-swipe#51]
Is there a handler in place to detect when the active item has changed? If not, any chances this could enter consideration?

**Comment by SharifClick** [comment]
Its necessary for many cases. Will add shortly. thanks @patrickjquinn 
What would be a nice name for that event/handler `on:swiped` `on:swipe_end` or in general `on:changed`? 
Or we need more handler? 
enlighten me.

**Comment by patrickjquinn** [comment]
`on:change` is probably the best of the 3? Mainly because it's the most idiomatic naming scheme that aligns with other standard events 😊 thanks for the response!
