### ISSUE TITLE
Images not visible in Safari.

### ISSUE THREAD

**Issue by lemnisk8** [SharifClick/svelte-swipe#6]
I have tried with both Safari and Safari Technology Preview, the SwiperItem images are not visible.

<img width="1915" alt="Screenshot 2019-12-24 at 4 43 24 PM" src="https://user-images.githubusercontent.com/1185625/71410761-910b9400-266c-11ea-88cd-32f3fe4f972f.png">

**Comment by SharifClick** [comment]
Thanks for this issue @lemnisk8 , this issue solved on current release v1.3.2
