### ISSUE TITLE
import does not work as presented

### ISSUE THREAD

**Issue by deuch13** [SharifClick/svelte-swipe#64]
The import statement ` import { Swipe, SwipeItem } from "svelte-swipe"` does not work as pacakge.json points to a file that doesn't exist at the specified location.

To be able to use the library the user needs to import using this path `import { Swipe, SwipeItem } from "svelte-swipe/src/lib/index`

**Comment by SharifClick** [comment]
Hi @deuch13, thank you for pointing this out.
released the patch just now, hope import will work
