### ISSUE TITLE
Initial slide index

### ISSUE THREAD

**Issue by SlyOtis** [SharifClick/svelte-swipe#7]
Hey, love that someone is taking the lead on creating this for Svelte. I'm currently trying to utilize this for page navigation in my app where it works somewhat as expected, but what is missing is an initial slide index setter.

**Comment by SlyOtis** [comment]
I have implemented this localy if you want the code just let me know. 🐆

**Comment by SharifClick** [comment]
hi @SlyOtis Thanks for your draws, PRs warmly appreciable

**Comment by SharifClick** [comment]
that feat added with new release :smiley: , now there is `defaultIndex` index setter prop :fire:
