### ISSUE TITLE
pls update to using svelte 4.0.0

### ISSUE THREAD

**Issue by anzbert** [SharifClick/svelte-swipe#71]
At the moment I am getting a warning from svelte-swipe:

```
Conflicting peer dependency: svelte@3.59.2
```

Would be great if you could adopt the latest major svelte version

Thx a lot!!!

**Comment by anzbert** [comment]
submitted a pull request...

**Comment by SharifClick** [comment]
Hi, released 2.0.0 with svelte 4 support 👍
