### ISSUE TITLE
When swiping the panel the active indicator doesn't change

### ISSUE THREAD

**Issue by neves-io** [SharifClick/svelte-swipe#75]
When swiping the panel the active indicator doesn't change, but when I click on the indicator it correctly changes. I'm also getting this error, not sure if it's linked:

`Swipe.svelte:78 Uncaught ReferenceError: fire is not defined
    at HTMLDivElement.<anonymous> (Swipe.svelte:78:7)
    at SwipeSnap.swipeEnd (SwipeSnap.js:235:18)
(anonymous) @ Swipe.svelte:78
swipeEnd @ SwipeSnap.js:235
Show 2 more frames
Show less`

**Comment by SharifClick** [comment]
Issue fixed on new release.
Thank you
